# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-01 02:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='log_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StatsCode', models.TextField()),
                ('URL', models.TextField()),
                ('Response', models.TextField()),
                ('SocketException', models.TextField()),
                ('Time', models.TextField()),
            ],
            options={
                'db_table': 'log_report',
            },
        ),
        migrations.CreateModel(
            name='NetTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DomainName', models.TextField()),
                ('MymeThod', models.TextField()),
                ('MyName', models.TextField()),
                ('Myurl', models.TextField()),
                ('ExpEcted', models.TextField()),
                ('Time', models.TextField()),
            ],
            options={
                'db_table': 'NetTest',
            },
        ),
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DomainName', models.TextField()),
                ('MymeThod', models.TextField()),
                ('MyName', models.TextField()),
                ('Myurl', models.TextField()),
                ('ExpEcted', models.TextField()),
                ('Time', models.TextField()),
            ],
            options={
                'db_table': 'person',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StatsCode', models.TextField()),
                ('URL', models.TextField()),
                ('Response', models.TextField()),
                ('Time', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=20)),
                ('sub_num', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Use_Cases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CaseDescription', models.TextField()),
                ('steps', models.TextField()),
                ('TestDescription', models.TextField()),
                ('TestObject', models.TextField()),
                ('PositioningWay', models.TextField()),
                ('TestObjectEntities', models.TextField()),
                ('OperationMethod', models.TextField()),
                ('TestData', models.TextField()),
                ('TestResults', models.TextField()),
                ('AssertionResults', models.TextField()),
            ],
            options={
                'db_table': 'Use_Cases',
            },
        ),
    ]
